monzo_take_home_test:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: analytics-take-home-test
      dataset: monzo_datawarehouse
      threads: 1
      timeout_seconds: 300
      location: US
      priority: interactive
